version: "3.7"

services:
  backend:
    image: servicosia/gestao-consultores:6.0.0
    networks:
      - network_public
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=seu_usuario
      - POSTGRES_PASSWORD=sua_senha_segura
      - POSTGRES_DATABASE=gestao_consultores
      - AUTHENTICATION_API_KEY=sua_api_key
      - ENVIRONMENT=production
      - API_URL=https://sua-api.exemplo.com
    ports:
      - "8000:8000"
    volumes:
      - api_gestao_consultores:/app/data
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.hostname == seu-hostname
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.gestao-consultores-api.rule=Host(`api.exemplo.com`)
        - traefik.http.routers.gestao-consultores-api.entrypoints=websecure
        - traefik.http.routers.gestao-consultores-api.tls.certresolver=letsencryptresolver
        - traefik.http.services.gestao-consultores-api.loadBalancer.server.port=8000

networks:
  network_public:
    external: true
    name: network_public

volumes:
  api_gestao_consultores:
    external: true
    name: api_gestao_consultores
